package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group  implements java.io.Serializable {


     private Integer GId;
     private String groupName;
     private String members;
     private Date lastUpdate;
     private Set postses = new HashSet(0);

    public Group() {
    }

	
    public Group(String groupName, String members, Date lastUpdate) {
        this.groupName = groupName;
        this.members = members;
        this.lastUpdate = lastUpdate;
    }
    public Group(String groupName, String members, Date lastUpdate, Set postses) {
       this.groupName = groupName;
       this.members = members;
       this.lastUpdate = lastUpdate;
       this.postses = postses;
    }
   
    public Integer getGId() {
        return this.GId;
    }
    
    public void setGId(Integer GId) {
        this.GId = GId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getMembers() {
        return this.members;
    }
    
    public void setMembers(String members) {
        this.members = members;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


