package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hashtag generated by hbm2java
 */
public class Hashtag  implements java.io.Serializable {


     private Integer HId;
     private Member member;
     private String tag;
     private String description;
     private String members;
     private Date lastUpdate;
     private Set postses = new HashSet(0);

    public Hashtag() {
    }

	
    public Hashtag(Member member, String tag, String description, String members, Date lastUpdate) {
        this.member = member;
        this.tag = tag;
        this.description = description;
        this.members = members;
        this.lastUpdate = lastUpdate;
    }
    public Hashtag(Member member, String tag, String description, String members, Date lastUpdate, Set postses) {
       this.member = member;
       this.tag = tag;
       this.description = description;
       this.members = members;
       this.lastUpdate = lastUpdate;
       this.postses = postses;
    }
   
    public Integer getHId() {
        return this.HId;
    }
    
    public void setHId(Integer HId) {
        this.HId = HId;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getMembers() {
        return this.members;
    }
    
    public void setMembers(String members) {
        this.members = members;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }




}


