package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer MId;
     private Team team;
     private String email;
     private String pass;
     private String username;
     private Date dob;
     private String privilige;
     private Set postses = new HashSet(0);
     private Set messagesesForReceiverId = new HashSet(0);
     private Set messagesesForSenderId = new HashSet(0);
     private Set hashtags = new HashSet(0);

    public Member() {
    }

	
    public Member(Team team, String email, String pass, String username, Date dob, String privilige) {
        this.team = team;
        this.email = email;
        this.pass = pass;
        this.username = username;
        this.dob = dob;
        this.privilige = privilige;
    }
    public Member(Team team, String email, String pass, String username, Date dob, String privilige, Set postses, Set messagesesForReceiverId, Set messagesesForSenderId, Set hashtags) {
       this.team = team;
       this.email = email;
       this.pass = pass;
       this.username = username;
       this.dob = dob;
       this.privilige = privilige;
       this.postses = postses;
       this.messagesesForReceiverId = messagesesForReceiverId;
       this.messagesesForSenderId = messagesesForSenderId;
       this.hashtags = hashtags;
    }
   
    public Integer getMId() {
        return this.MId;
    }
    
    public void setMId(Integer MId) {
        this.MId = MId;
    }
    public Team getTeam() {
        return this.team;
    }
    
    public void setTeam(Team team) {
        this.team = team;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getPrivilige() {
        return this.privilige;
    }
    
    public void setPrivilige(String privilige) {
        this.privilige = privilige;
    }
    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }
    public Set getMessagesesForReceiverId() {
        return this.messagesesForReceiverId;
    }
    
    public void setMessagesesForReceiverId(Set messagesesForReceiverId) {
        this.messagesesForReceiverId = messagesesForReceiverId;
    }
    public Set getMessagesesForSenderId() {
        return this.messagesesForSenderId;
    }
    
    public void setMessagesesForSenderId(Set messagesesForSenderId) {
        this.messagesesForSenderId = messagesesForSenderId;
    }
    public Set getHashtags() {
        return this.hashtags;
    }
    
    public void setHashtags(Set hashtags) {
        this.hashtags = hashtags;
    }




}


