package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer messageId;
     private Member memberByReceiverId;
     private Member memberBySenderId;
     private String body;
     private Date lastUpdate;

    public Messages() {
    }

    public Messages(Member memberByReceiverId, Member memberBySenderId, String body, Date lastUpdate) {
       this.memberByReceiverId = memberByReceiverId;
       this.memberBySenderId = memberBySenderId;
       this.body = body;
       this.lastUpdate = lastUpdate;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public Member getMemberByReceiverId() {
        return this.memberByReceiverId;
    }
    
    public void setMemberByReceiverId(Member memberByReceiverId) {
        this.memberByReceiverId = memberByReceiverId;
    }
    public Member getMemberBySenderId() {
        return this.memberBySenderId;
    }
    
    public void setMemberBySenderId(Member memberBySenderId) {
        this.memberBySenderId = memberBySenderId;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


