package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Posts generated by hbm2java
 */
public class Posts  implements java.io.Serializable {


     private Integer PId;
     private Group group;
     private Hashtag hashtag;
     private Member member;
     private String postDescription;
     private String type;
     private Date lastUpdate;

    public Posts() {
    }

	
    public Posts(Member member, String postDescription, String type, Date lastUpdate) {
        this.member = member;
        this.postDescription = postDescription;
        this.type = type;
        this.lastUpdate = lastUpdate;
    }
    public Posts(Group group, Hashtag hashtag, Member member, String postDescription, String type, Date lastUpdate) {
       this.group = group;
       this.hashtag = hashtag;
       this.member = member;
       this.postDescription = postDescription;
       this.type = type;
       this.lastUpdate = lastUpdate;
    }
   
    public Integer getPId() {
        return this.PId;
    }
    
    public void setPId(Integer PId) {
        this.PId = PId;
    }
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }
    public Hashtag getHashtag() {
        return this.hashtag;
    }
    
    public void setHashtag(Hashtag hashtag) {
        this.hashtag = hashtag;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getPostDescription() {
        return this.postDescription;
    }
    
    public void setPostDescription(String postDescription) {
        this.postDescription = postDescription;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


