package com.pro;
// Generated 15 Jul, 2015 4:58:04 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team  implements java.io.Serializable {


     private Integer TId;
     private String teamName;
     private String teamDescription;
     private Date lastUpdate;
     private Set members = new HashSet(0);

    public Team() {
    }

	
    public Team(String teamName, String teamDescription, Date lastUpdate) {
        this.teamName = teamName;
        this.teamDescription = teamDescription;
        this.lastUpdate = lastUpdate;
    }
    public Team(String teamName, String teamDescription, Date lastUpdate, Set members) {
       this.teamName = teamName;
       this.teamDescription = teamDescription;
       this.lastUpdate = lastUpdate;
       this.members = members;
    }
   
    public Integer getTId() {
        return this.TId;
    }
    
    public void setTId(Integer TId) {
        this.TId = TId;
    }
    public String getTeamName() {
        return this.teamName;
    }
    
    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }
    public String getTeamDescription() {
        return this.teamDescription;
    }
    
    public void setTeamDescription(String teamDescription) {
        this.teamDescription = teamDescription;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }




}


